apiVersion: v1
kind: Service
metadata:
  name: {{ include "permissionservice.fullname" . }}
  labels:
    {{- include "permissionservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "permissionservice.selectorLabels" . | nindent 4 }}
